<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hotel extends Model
{
    use HasFactory;
    protected $fillable = [
        'hotel_name',
        'hotel_phone',
        'hotel_about',
        'hotel_email',
        'hotel_category',
        'hotel_type',
        'hotel_minimum_nights',
        'security_deposit',
        'longitude',
        'latitude',
        'city',
        'hotel_amenities',
        'hotel_amenities1',
        'hotel_amenities2',
        'hotel_amenities3',
        'hotel_amenities4',
        'hotel_amenities5',
        'hotel_amenities6',
        'hotel_amenities7',
        'hotel_amenities8',
        'hotel_amenities9',
        'hotel_amenities10',
        'hotel_amenities11',
        'hotel_amenities12',
        'hotel_amenities13',
        'hotel_amenities14',
        'hotel_amenities15',
        'hotel_amenities16',
        'hotel_amenities17',
        'hotel_amenities18',
        'hotel_amenities19',
        'hotel_amenities20',
        'hotel_amenities21',
        'hotel_amenities22',
        'hotel_amenities23',
        'hotel_amenities24',
        'hotel_amenities25',
        'hotel_amenities26',
        'hotel_amenities27',
        'hotel_amenities28',
        'hotel_amenities29',
        'hotel_amenities30',
        'hotel_amenities31',
        'hotel_amenities32',
        'hotel_amenities33',
        'hotel_amenities34',
        'hotel_amenities35',
        'hotel_amenities36',
        'hotel_amenities37',
        'hotel_amenities38',
        'hotel_amenities39',
        'hotel_amenities40',
        'hotel_amenities41',
        'hotel_amenities42',
        'hotel_amenities43',
        'hotel_amenities44',
        'hotel_amenities45',
        'hotel_amenities46',
        'hotel_amenities47',
        'hotel_amenities48',
        'hotel_amenities49',
        'hotel_amenities50',
    ];
}
