<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    use HasFactory;
    protected $fillable = [
        'room_id',
        'room_name',
        'room_feet',
        'room_bed_type',
        'room_bathroom_type',
        'room_amount',
        'room_amenities',
        'room_amenities1',
        'room_amenities2',
        'room_amenities3',
        'room_amenities4',
        'room_amenities5',
        'room_amenities6',
        'room_amenities7',
        'room_amenities8',
        'room_amenities9',
        'room_amenities10',
        'room_amenities11',
        'room_amenities12',
        'room_amenities13',
        'room_amenities14',
        'room_amenities15',
        'room_amenities16',
        'room_amenities17',
        'room_amenities18',
        'room_amenities19',
        'room_amenities20',
        'room_amenities21',
        'room_amenities22',
        'room_amenities23',
        'room_amenities24',
        'room_amenities25',
        'room_amenities26',
        'room_amenities27',
        'room_amenities28',
        'room_amenities29',
        'room_amenities30',
        'room_amenities31',
        'room_amenities32',
        'room_amenities33',
        'room_amenities34',
        'room_amenities35',
        'room_amenities36',
        'room_amenities37',
        'room_amenities38',
        'room_amenities39',
        'room_amenities40',
        'room_amenities41',
        'room_amenities42',
        'room_amenities43',
        'room_amenities44',
        'room_amenities45',
        'room_amenities46',
        'room_amenities47',
        'room_amenities48',
        'room_amenities49',
        'room_amenities50',
    ];
}
